# Generated by Django 4.1 on 2023-03-25 23:04

import backend.metamask.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAuthModel",
            fields=[
                ("public_address", models.TextField(primary_key=True, serialize=False)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="NonCustodialWallet",
            fields=[
                (
                    "walletauthmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="metamask.walletauthmodel",
                    ),
                ),
                (
                    "nonce",
                    models.TextField(default=backend.metamask.utils.generate_random),
                ),
                ("nonce_stale", models.BooleanField(default=False)),
                (
                    "refreshed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Refreshed"),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("metamask.walletauthmodel",),
        ),
    ]
