# Generated by Django 4.1 on 2023-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manufacturer", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="token",
            field=models.CharField(max_length=10),
        ),
    ]
